jobs:
- job: ExampleJob
  displayName: Example Job
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      echo "This build will fail intentionally"
      exit 1
    displayName: 'Task 1'
  - bash: |
      echo "This build will fail intentionally"
      exit 1
    displayName: 'Task 2'
  - bash: |
      echo "This will run if any task fails"
      exit 0
    displayName: 'Task 3'
    continueOnError: true
    condition: failed()

