jobs:
- job: ExampleJob1
  displayName: Example Job1
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      echo "This build will fail intentionally"
      exit 0
    displayName: 'Task 1.1'
  - bash: |
      echo "This build will fail intentionally"
      exit 1
    displayName: 'Task 1.2'

- job: ExampleJob2
  displayName: Example Job2
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      echo "This build will fail intentionally"
      exit 0
    displayName: 'Task 1'
  - bash: |
      echo "This build will fail intentionally"
      exit 0
    displayName: 'Task 2'

- job: LastJob
  dependsOn:
    - ExampleJob1
    - ExampleJob2
  condition: and(failed(), in(variables['Build.Reason'], 'IndividualCI', 'Manual'))
  displayName: Last Job
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.10'
    inputs:
      versionSpec: 3.10
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure CLI'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        teams_api_url = $(az keyvault secret show --vault-name kv-azuresdk --name azure-cli-teams-bot-api-url --query value -otsv)
        teams_api_key = $(az keyvault secret show --vault-name kv-azuresdk --name azure-cli-teams-bot-api-key --query value -otsv)
        echo "If any task fails, notify to teams channel"
        python scripts/ci/notify_ci_errors.py $teams_api_url $teams_api_key
    displayName: 'Task 3'
    env:
      BASE_URI: $(System.CollectionUri)
      PROJECT_TYPE: $(System.TeamProject)
      BUILD_ID: $(Build.BuildId)
      JOB_ID: $(System.JobId)