jobs:
- job: ExampleJob
  displayName: Example Job
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      echo "This build will fail intentionally"
      exit 1
    displayName: 'Task 1'
  - bash: |
      echo "This build will fail intentionally"
      exit 0
    displayName: 'Task 2'
  - bash: |
      echo "This will run if any task fails"
      # public
      echo $(System.TeamProject)
      # id
      echo $(Build.BuildId)
      # https://dev.azure.com/azclitools/
      echo $(System.TeamFoundationCollectionUri)
      echo $(System.CollectionUri)
      echo $(System.JobId)
      echo $(System.TimelineId)
      exit 0
    displayName: 'Task 3'
    continueOnError: true
    condition: failed()

