jobs:
- job: ExampleJob
  displayName: Example Job
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Task1
    displayName: 'Task 1'
    script: |
      echo "This build will fail intentionally"
      exit 1
  - task: Task2
    displayName: 'Task 2'
    script: |
      echo "This build will fail intentionally"
      exit 1
  - task: Task3
    displayName: 'Task 3'
    continueOnError: true
    condition: failed()
    script: |
      echo "This will run if any task fails"
      exit 0
