# Some content of this file is generated.

trigger:
  branches:
    exclude:
    - '*'

variables:
- template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/variables.yml

parameters:
- name: versions
  type: object
  default:
    python36: "3.6"
    python37: "3.7"
    python38: "3.8"
    python39: "3.9"
    python310: "3.10"
    python311: "3.11"

jobs:
- job: getPythonVersion
  displayName: "get Python Version"
  pool:
    name: 'pool-ubuntu-2004'
  steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.10'
      inputs:
        versionSpec: '3.10'
    - bash: |
        #!/usr/bin/env bash
        set -ev

        echo "3.6 3.7 3.8 3.9 3.10 3.11" > python_version.txt
        pythonVersion=`cat python_version.txt`
        echo $pythonVersion
        echo "##vso[task.setvariable variable=pythonVersion;isoutput=true]$pythonVersion"
      name: CustomParas
      displayName: 'get Python Version'
      env:
        ADO_PULL_REQUEST_LATEST_COMMIT: HEAD
        ADO_PULL_REQUEST_TARGET_BRANCH: $(System.PullRequest.TargetBranch)

- ${{each version in parameters.versions}}:
  - job: test${{version.key}}
    dependsOn: getPythonVersion
    variables:
      PythonVersion: $[ dependencies.getPythonVersion.outputs['CustomParas.pythonVersion'] ]
    condition: and(succeeded(), contains(variables.PythonVersion, ${{version.value}}))
    displayName: "test ${{version.key}}"
    pool:
      name: ${{ variables.ubuntu_pool }}
    timeoutInMinutes: 0
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use ${{version.key}}'
        inputs:
          versionSpec: '${{version.value}}'
      - bash: |
          #!/bin/bash
          python -V
